export const REGISTER_FORM_ACTIONS = {
	EMAIL_CHANGED: 'EMAIL_CHANGED',
	PASSWORD_CHANGED: 'PASSWORD_CHANGED',
	CONFIRM_PASSWORD_CHANGED: 'CONFIRM_PASSWORD_CHANGED',
	EMAIL_ERROR_CHANGED: 'EMAIL_ERROR_CHANGED',
	PASSWORD_ERROR_CHANGED: 'PASSWORD_ERROR_CHANGED',
	CONFIRM_PASSWORD_ERROR_CHANGED: 'CONFIRM_PASSWORD_ERROR_CHANGED'
};
